

const LOAD_POSTS = "LOAD_POSTS"
const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"
const LOAD_POST_ERROR = "LOAD_POST_ERROR"
const ADD_POST = "ADD_POST"
const DELETE_POST = "DELETE_POST"

export {
    LOAD_POSTS,
    LOAD_POSTS_SUCCESS,
    LOAD_POST_ERROR ,
    ADD_POST,
    DELETE_POST
}