

const LOAD_POSTS = "LOAD_POSTS"
const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS"
const LOAD_POST_ERROR = "LOAD_POST_ERROR"
const ADD_POST = "ADD_POST"
const DELETE_POST = "DELETE_POST"

const SHOW_AVAILABLE_MODAL = "SHOW_AVAILABLE_MODAL"
const HIDE_AVAILABLE_MODAL = "HIDE_AVAILABLE_MODAL"

export {
    LOAD_POSTS,
    LOAD_POSTS_SUCCESS,
    LOAD_POST_ERROR ,
    ADD_POST,
    DELETE_POST,
    SHOW_AVAILABLE_MODAL,
    HIDE_AVAILABLE_MODAL
}